version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: | 
          npm run build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: dist
          # Must be relative path from root
          paths:
            - echo-output
  two:
    docker: # it uses the docker executor
      - image: ubuntu:18.04
  
    steps:
      - checkout 
      - attach-workspace:
          at: dist/
      - run: ls
