version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: building artefact of boilerplate
          command: |
            npm run build
          
