version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    working_directory: ~/project/boiler
    steps:
      - checkout
      - node/install-packages:
          app-dir: boiler
          with-cache: true
          override-ci-command: npm install
      - run: |
          cd boiler
          npm run build
