version: 2.1

# orbs:
#   node: circleci/node@4.1.0

jobs:
  build_boiler:
    docker:
      - image: circleci/node@4.1.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # - node/install-packages:
      #     app-dir: boiler
      #     with-cache: true
      #     override-ci-command: npm install
      - run: |
          cd boiler
          npm install
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "boiler/package-lock.json" }}
      - run: |
          cd boiler
          npm run build
          ls
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "boiler/package-lock.json" }}

      - persist_to_workspace:
          root: boiler/dist
          paths:
            - .
